// This file is generated by rust-protobuf 2.27.1. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `src/proto/server_config/server_config.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_27_1;

#[derive(PartialEq,Clone,Default,Debug)]
pub struct ServerConfig {
    // message fields
    pub pubkey: ::protobuf::SingularField<::std::vec::Vec<u8>>,
    pub route_hash: ::protobuf::SingularField<::std::vec::Vec<u8>>,
    pub enc_method: ::protobuf::SingularField<::std::string::String>,
    pub client_platform_type: ::protobuf::SingularField<::std::string::String>,
    pub client_platform_version: ::protobuf::SingularField<::std::string::String>,
    pub client_platform_category: ::protobuf::SingularField<::std::string::String>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a ServerConfig {
    fn default() -> &'a ServerConfig {
        <ServerConfig as ::protobuf::Message>::default_instance()
    }
}

impl ServerConfig {
    pub fn new() -> ServerConfig {
        ::std::default::Default::default()
    }

    // optional bytes pubkey = 1;


    pub fn get_pubkey(&self) -> &[u8] {
        match self.pubkey.as_ref() {
            Some(v) => &v,
            None => &[],
        }
    }
    pub fn clear_pubkey(&mut self) {
        self.pubkey.clear();
    }

    pub fn has_pubkey(&self) -> bool {
        self.pubkey.is_some()
    }

    // Param is passed by value, moved
    pub fn set_pubkey(&mut self, v: ::std::vec::Vec<u8>) {
        self.pubkey = ::protobuf::SingularField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_pubkey(&mut self) -> &mut ::std::vec::Vec<u8> {
        if self.pubkey.is_none() {
            self.pubkey.set_default();
        }
        self.pubkey.as_mut().unwrap()
    }

    // Take field
    pub fn take_pubkey(&mut self) -> ::std::vec::Vec<u8> {
        self.pubkey.take().unwrap_or_else(|| ::std::vec::Vec::new())
    }

    // optional bytes route_hash = 2;


    pub fn get_route_hash(&self) -> &[u8] {
        match self.route_hash.as_ref() {
            Some(v) => &v,
            None => &[],
        }
    }
    pub fn clear_route_hash(&mut self) {
        self.route_hash.clear();
    }

    pub fn has_route_hash(&self) -> bool {
        self.route_hash.is_some()
    }

    // Param is passed by value, moved
    pub fn set_route_hash(&mut self, v: ::std::vec::Vec<u8>) {
        self.route_hash = ::protobuf::SingularField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_route_hash(&mut self) -> &mut ::std::vec::Vec<u8> {
        if self.route_hash.is_none() {
            self.route_hash.set_default();
        }
        self.route_hash.as_mut().unwrap()
    }

    // Take field
    pub fn take_route_hash(&mut self) -> ::std::vec::Vec<u8> {
        self.route_hash.take().unwrap_or_else(|| ::std::vec::Vec::new())
    }

    // optional string enc_method = 3;


    pub fn get_enc_method(&self) -> &str {
        match self.enc_method.as_ref() {
            Some(v) => &v,
            None => "",
        }
    }
    pub fn clear_enc_method(&mut self) {
        self.enc_method.clear();
    }

    pub fn has_enc_method(&self) -> bool {
        self.enc_method.is_some()
    }

    // Param is passed by value, moved
    pub fn set_enc_method(&mut self, v: ::std::string::String) {
        self.enc_method = ::protobuf::SingularField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_enc_method(&mut self) -> &mut ::std::string::String {
        if self.enc_method.is_none() {
            self.enc_method.set_default();
        }
        self.enc_method.as_mut().unwrap()
    }

    // Take field
    pub fn take_enc_method(&mut self) -> ::std::string::String {
        self.enc_method.take().unwrap_or_else(|| ::std::string::String::new())
    }

    // optional string client_platform_type = 4;


    pub fn get_client_platform_type(&self) -> &str {
        match self.client_platform_type.as_ref() {
            Some(v) => &v,
            None => "",
        }
    }
    pub fn clear_client_platform_type(&mut self) {
        self.client_platform_type.clear();
    }

    pub fn has_client_platform_type(&self) -> bool {
        self.client_platform_type.is_some()
    }

    // Param is passed by value, moved
    pub fn set_client_platform_type(&mut self, v: ::std::string::String) {
        self.client_platform_type = ::protobuf::SingularField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_client_platform_type(&mut self) -> &mut ::std::string::String {
        if self.client_platform_type.is_none() {
            self.client_platform_type.set_default();
        }
        self.client_platform_type.as_mut().unwrap()
    }

    // Take field
    pub fn take_client_platform_type(&mut self) -> ::std::string::String {
        self.client_platform_type.take().unwrap_or_else(|| ::std::string::String::new())
    }

    // optional string client_platform_version = 5;


    pub fn get_client_platform_version(&self) -> &str {
        match self.client_platform_version.as_ref() {
            Some(v) => &v,
            None => "",
        }
    }
    pub fn clear_client_platform_version(&mut self) {
        self.client_platform_version.clear();
    }

    pub fn has_client_platform_version(&self) -> bool {
        self.client_platform_version.is_some()
    }

    // Param is passed by value, moved
    pub fn set_client_platform_version(&mut self, v: ::std::string::String) {
        self.client_platform_version = ::protobuf::SingularField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_client_platform_version(&mut self) -> &mut ::std::string::String {
        if self.client_platform_version.is_none() {
            self.client_platform_version.set_default();
        }
        self.client_platform_version.as_mut().unwrap()
    }

    // Take field
    pub fn take_client_platform_version(&mut self) -> ::std::string::String {
        self.client_platform_version.take().unwrap_or_else(|| ::std::string::String::new())
    }

    // optional string client_platform_category = 6;


    pub fn get_client_platform_category(&self) -> &str {
        match self.client_platform_category.as_ref() {
            Some(v) => &v,
            None => "",
        }
    }
    pub fn clear_client_platform_category(&mut self) {
        self.client_platform_category.clear();
    }

    pub fn has_client_platform_category(&self) -> bool {
        self.client_platform_category.is_some()
    }

    // Param is passed by value, moved
    pub fn set_client_platform_category(&mut self, v: ::std::string::String) {
        self.client_platform_category = ::protobuf::SingularField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_client_platform_category(&mut self) -> &mut ::std::string::String {
        if self.client_platform_category.is_none() {
            self.client_platform_category.set_default();
        }
        self.client_platform_category.as_mut().unwrap()
    }

    // Take field
    pub fn take_client_platform_category(&mut self) -> ::std::string::String {
        self.client_platform_category.take().unwrap_or_else(|| ::std::string::String::new())
    }
}

impl ::protobuf::Message for ServerConfig {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_bytes_into(wire_type, is, &mut self.pubkey)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_bytes_into(wire_type, is, &mut self.route_hash)?;
                },
                3 => {
                    ::protobuf::rt::read_singular_string_into(wire_type, is, &mut self.enc_method)?;
                },
                4 => {
                    ::protobuf::rt::read_singular_string_into(wire_type, is, &mut self.client_platform_type)?;
                },
                5 => {
                    ::protobuf::rt::read_singular_string_into(wire_type, is, &mut self.client_platform_version)?;
                },
                6 => {
                    ::protobuf::rt::read_singular_string_into(wire_type, is, &mut self.client_platform_category)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.pubkey.as_ref() {
            my_size += ::protobuf::rt::bytes_size(1, &v);
        }
        if let Some(ref v) = self.route_hash.as_ref() {
            my_size += ::protobuf::rt::bytes_size(2, &v);
        }
        if let Some(ref v) = self.enc_method.as_ref() {
            my_size += ::protobuf::rt::string_size(3, &v);
        }
        if let Some(ref v) = self.client_platform_type.as_ref() {
            my_size += ::protobuf::rt::string_size(4, &v);
        }
        if let Some(ref v) = self.client_platform_version.as_ref() {
            my_size += ::protobuf::rt::string_size(5, &v);
        }
        if let Some(ref v) = self.client_platform_category.as_ref() {
            my_size += ::protobuf::rt::string_size(6, &v);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.pubkey.as_ref() {
            os.write_bytes(1, &v)?;
        }
        if let Some(ref v) = self.route_hash.as_ref() {
            os.write_bytes(2, &v)?;
        }
        if let Some(ref v) = self.enc_method.as_ref() {
            os.write_string(3, &v)?;
        }
        if let Some(ref v) = self.client_platform_type.as_ref() {
            os.write_string(4, &v)?;
        }
        if let Some(ref v) = self.client_platform_version.as_ref() {
            os.write_string(5, &v)?;
        }
        if let Some(ref v) = self.client_platform_category.as_ref() {
            os.write_string(6, &v)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> ServerConfig {
        ServerConfig::new()
    }

    fn default_instance() -> &'static ServerConfig {
        static instance: ::protobuf::rt::LazyV2<ServerConfig> = ::protobuf::rt::LazyV2::INIT;
        instance.get(ServerConfig::new)
    }
}

impl ::protobuf::Clear for ServerConfig {
    fn clear(&mut self) {
        self.pubkey.clear();
        self.route_hash.clear();
        self.enc_method.clear();
        self.client_platform_type.clear();
        self.client_platform_version.clear();
        self.client_platform_category.clear();
        self.unknown_fields.clear();
    }
}

impl ::protobuf::reflect::ProtobufValue for ServerConfig {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default,Debug)]
pub struct Route {
    // message fields
    pub route: ::protobuf::SingularField<::std::string::String>,
    pub route_hash: ::protobuf::SingularField<::std::vec::Vec<u8>>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a Route {
    fn default() -> &'a Route {
        <Route as ::protobuf::Message>::default_instance()
    }
}

impl Route {
    pub fn new() -> Route {
        ::std::default::Default::default()
    }

    // optional string route = 1;


    pub fn get_route(&self) -> &str {
        match self.route.as_ref() {
            Some(v) => &v,
            None => "",
        }
    }
    pub fn clear_route(&mut self) {
        self.route.clear();
    }

    pub fn has_route(&self) -> bool {
        self.route.is_some()
    }

    // Param is passed by value, moved
    pub fn set_route(&mut self, v: ::std::string::String) {
        self.route = ::protobuf::SingularField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_route(&mut self) -> &mut ::std::string::String {
        if self.route.is_none() {
            self.route.set_default();
        }
        self.route.as_mut().unwrap()
    }

    // Take field
    pub fn take_route(&mut self) -> ::std::string::String {
        self.route.take().unwrap_or_else(|| ::std::string::String::new())
    }

    // optional bytes route_hash = 2;


    pub fn get_route_hash(&self) -> &[u8] {
        match self.route_hash.as_ref() {
            Some(v) => &v,
            None => &[],
        }
    }
    pub fn clear_route_hash(&mut self) {
        self.route_hash.clear();
    }

    pub fn has_route_hash(&self) -> bool {
        self.route_hash.is_some()
    }

    // Param is passed by value, moved
    pub fn set_route_hash(&mut self, v: ::std::vec::Vec<u8>) {
        self.route_hash = ::protobuf::SingularField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_route_hash(&mut self) -> &mut ::std::vec::Vec<u8> {
        if self.route_hash.is_none() {
            self.route_hash.set_default();
        }
        self.route_hash.as_mut().unwrap()
    }

    // Take field
    pub fn take_route_hash(&mut self) -> ::std::vec::Vec<u8> {
        self.route_hash.take().unwrap_or_else(|| ::std::vec::Vec::new())
    }
}

impl ::protobuf::Message for Route {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_string_into(wire_type, is, &mut self.route)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_bytes_into(wire_type, is, &mut self.route_hash)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.route.as_ref() {
            my_size += ::protobuf::rt::string_size(1, &v);
        }
        if let Some(ref v) = self.route_hash.as_ref() {
            my_size += ::protobuf::rt::bytes_size(2, &v);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.route.as_ref() {
            os.write_string(1, &v)?;
        }
        if let Some(ref v) = self.route_hash.as_ref() {
            os.write_bytes(2, &v)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Route {
        Route::new()
    }

    fn default_instance() -> &'static Route {
        static instance: ::protobuf::rt::LazyV2<Route> = ::protobuf::rt::LazyV2::INIT;
        instance.get(Route::new)
    }
}

impl ::protobuf::Clear for Route {
    fn clear(&mut self) {
        self.route.clear();
        self.route_hash.clear();
        self.unknown_fields.clear();
    }
}

impl ::protobuf::reflect::ProtobufValue for Route {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}
